# Generated by Django 4.1.3 on 2022-11-20 14:42

import django.core.validators
from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):


    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[helpers.validators.validate_alphabet_characters, django.core.validators.MinLengthValidator(2)])),
                ('subject', models.CharField(max_length=50, validators=[helpers.validators.validate_alphabet_characters, django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_received', models.DateField(auto_now_add=True)),
                ('reply', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Form',
            },
        ),
    ]
