# Generated by Django 4.1.3 on 2022-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
