# Generated by Django 4.1.3 on 2022-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_tag_blogpost_tagged_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/', verbose_name='Image'),
        ),
    ]
