# Generated by Django 4.1.3 on 2022-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_alter_blogpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tagged_posts',
            field=models.ManyToManyField(blank=True, null=True, to='blogpost.tag'),
        ),
    ]
