# Generated by Django 4.1.3 on 2022-12-11 08:33

import django.core.validators
from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_additional_links_and_subscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionallinkinformation',
            name='subsection_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='additionallinkinformation',
            name='section_name',
            field=models.CharField(max_length=30, unique=True, validators=[helpers.validators.validate_alphabet_characters, django.core.validators.MinLengthValidator(4)]),
        ),
    ]
