# Generated by Django 4.1.3 on 2022-12-11 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionallinkinformation_subsection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('subsection_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='additionallinkinformation',
            name='subsection_name',
        ),
        migrations.AddField(
            model_name='additionallinkinformation',
            name='subsections',
            field=models.ManyToManyField(blank=True, null=True, to='main.subsections'),
        ),
    ]
