# Generated by Django 4.1.3 on 2022-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subsections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsections',
            options={'verbose_name_plural': 'Subsections'},
        ),
        migrations.AlterField(
            model_name='additionallinkinformation',
            name='subsections',
            field=models.ManyToManyField(blank=True, to='main.subsections'),
        ),
    ]
