# Generated by Django 4.1.3 on 2022-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0002_appuser_city_appuser_phone_number_appuser_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='additional_address_info',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
