# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models
import sweetshop.webusers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0003_appuser_additional_address_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='additional_address_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[sweetshop.webusers.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[sweetshop.webusers.validators.validate_only_digits]),
        ),
    ]
